# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Uddhav Dave
title: IoT Systems Engineer
email: uddhavdave@protonmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: you_da_way
github_username:  uddhavdave
linkedin_username: uddhav-dave-a17259122

# Additional icon links
additional_links:
- title: Medium
  icon: fab fa-medium 
  url: https://medium.com/@uddhavdave1
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://media-exp1.licdn.com/dms/image/C4E03AQFuhGjDFWKq9g/profile-displayphoto-shrink_800_800/0/1630222617013?e=1639008000&v=beta&t=2DrduQRpcLHBT34_Opf7JNgXpQtFpr2WSJFZ16BtBUU
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Uddhav Dave, I'm an IoT Engineer with 2 years experience, currently specializing in FreeRTOS devices supporting Wifi/BLE stack. I enjoy working on Systems Architecture, Distributed Systems, Automation Scripting and Network Programming. 

  Some Skills i have acquired so far:
  - <mark>Programming Languages</mark> [**C**, **RustLang**, **Python**] 
  - <mark>Communication Protocols</mark> [**WiFi**, **BLE**, **MQTT**, **UART**]
  - <mark>OS Level programming</mark> [**FreeRTOS**, **Linux**]
  - <mark>Blockchain Development</mark> [**<a href="https://substrate.dev/">Substrate</a>**, **<a href="https://solana.com/ecosystem/anchor">Anchor</a>**]
  
  And I am really excited to add more.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Reliance Jio
        sub_title: Senior IoT Engineer (Embedded Systems)
        caption: November 2019 - present
        quote: >
          Developer - Internet of Things
        description: | # this will include new lines to allow paragraphs
          I am currently working in Jio Devices, specifically handling inclusion of devices in the IoT ecosystem. My work includes designing and developing safe and high performance firmware for smart devices in home automation services and work closely with App/Cloud teams to deliver client requirements. I heavily use <mark>C</mark> and <mark>Python</mark> to perform these tasks and work with low level system concepts such as <mark>Bootloader</mark> and <mark>NVS</mark> for embedded devices.

          Being the person who is ready to learn and implement new topics with speed and competency, I have received exposure to multiple aspects of an IoT ecosystem Product. Amongst such topics is <mark>MQTT</mark>, <mark>WiFi</mark>, <mark>BLE</mark>, <mark>SIA-DC09</mark> and various proprietary protocols. Apart from communication protocols, I have gained very good experience on developing Firmware on <mark>FreeRTOS</mark> and apps in <mark>embedded Linux</mark>, and also have applied security algorithms such as <mark>AES</mark>, <mark>RSA</mark> and <mark>SHA/MD5</mark> Checksum validation to our solutions.

          I enjoy learning about all areas of our application which allows me to be a go-to person for knowledge and queries within my team and the other teams in the office. I am always looking to suggest improvements and challenge what and how we are working to make sure we are delivering the best service to the customers while also developing to the highest standards.
      - layout: left
        title: Reliance Jio
        sub_title: GIS Engineer Intern
        caption: December 2018 - January 2019
        quote: >
          Internship - Geographical Information Systems
        description: | # this will include new lines to allow paragraphs
          While working as an intern in the GIS Department in Jio, i worked on clusters of geographical data and performed analysis on the same using <mark>ArcGIS</mark> and its python library to write scripts. Here i received Hands-on Experience on <mark>Geo-processing</mark>, <mark>Geo-mapping</mark> and using various tools to filter the Geographical vector data.

          I wrote multiple <mark>Python scripts</mark> to automate some repetitive tasks for the GIS team. This was the first time I was able to see real benefits of automating stuff, and has always inspired me to look into things through this perspective.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: Left
        title: Savant Monk
        link: https://github.com/uddhavdave/Sage 
        link_text: Source Code
        additional_links:
          - title:  uddhavdave/Sage
            icon: fab fa-github
            url: https://github.com/uddhavdave/Sage 
        quote: >
          Discord Bot for book Club Management
        description: | # this will include new lines to allow paragraphs
          Managing a Discord Book Club can be messy sometimes, and this bot gives you a helping hand. It keeps the server alive by posting some engaging messages and thoughtful quotes from various websites(<mark>API</mark> integration).
          It manages subscriptions to the quotes and suggestions by storing the metadata in a <mark>MongoDB</mark> instance. The bot is purely made on <mark>Rust</mark> to ensure speed and safety.
      - layout: Left
        title: Maximizing ROE Factor
        link: https://github.com/uddhavdave/Maximizing-ROE-Factor-
        link_text: Source Code
        additional_links:
          - title:  uddhavdave/Maximizing-ROE-Factor-
            icon: fab fa-github
            url: https://github.com/uddhavdave/Maximizing-ROE-Factor- 
        quote: >
          University Major Project
        description: | # this will include new lines to allow paragraphs
          Trained a <mark>Machine learning</mark> model using Genetic Algorithm and Linear Regression techniques to predict the price of a stock using <mark>MATLAB</mark>. This output was then used in an self implemented algorithm inspired from long term investment trading techniques written in <mark>Python</mark>. This application maximized the ROE factor of a company by considering input from the trained model and 6 technical indicators with an average accuracy of 67%.
      - layout: Left
        title: TicTacToe
        link: https://github.com/uddhavdave/tictactoe 
        link_text: Source Code
        additional_links:
          - title:  uddhavdave/tictactoe
            icon: fab fa-github
            url: https://github.com/uddhavdave/tictactoe 
        quote: >
          Intro to Rust programming
        description: | # this will include new lines to allow paragraphs
          Simple Command Line game in <mark>Rust</mark>. Here, I added a AI player which follows a set of moves depending whether it goes first or not. (*Challenge*: Try to win!)
  - title: Education
    layout: list
    content:
      - layout: Left
        title: SRM Institute of Science and Technology, Kattankulathur
        sub_title: B.Tech Software Engineering
        caption: 2015-2019
        quote: >
          74.4%
        description: | # this will include new lines to allow paragraphs
          The four-year undergraduate course provided with a broad understanding of the core principles of software engineering and its practicality in field.
      - layout: Left
        title: Bright School CBSE
        sub_title: SSC 
        caption: 2013-2015
        quote: >
          82.0%
        description: | # this will include new lines to allow paragraphs
          Opted for Computer science, where I learned programming in C/C++, along with HTML and SQL. This laid the foundation of my career. 
  - title: A Little More About Me
    layout: text
    content: |  # this will include new lines to allow paragraphs
      Apart from Professional work, I always try to contribute to Open-Source and learn new trends in the market to keep my skills relevant. I have completed multiple courses on <mark>Deep learning</mark>, and implemented it in some small scale side projects. Currently, my latest obsession is <mark>Blockchain Development</mark>, where i try to implement Smart Contracts on blockchains like <a href="https://solana.com/ecosystem/anchor">Solana</a> and <a href="https://substrate.dev/">Polkadot</a>.

      But when I am not at my Desk, you can find me cycling around the Town or playing Table-Tennis with my friends. Additionally, Watching E-sports, Playing Survival Games and, clicking Long-Exposure and Macro photographs are some hobbies which I thoroughly enjoy.   

  - title: 
    layout: text
    content: |
      ![alt text](/images/kc.png "PacMan")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
